[Definition]
datepattern = ^%%Y-%%m-%%d[Tt]%%H:%%M:%%S(?:[.,]%%f)?(?:[+-]%%z)?
failregex = ^<DATE>\t.*\trejected\s+connection\s+from\s+<HOST>.*$
            ^<DATE>\t.*\tinvalid.*from\s+<HOST>.*$
ignoreregex =